app = "voicebot-fly"
primary_region = "ams"

[env]
  BOT_TOKEN=""
  ADMINS=""

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[[services]]
  internal_port = 8080
  protocol = "tcp"